### ISSUE TITLE
惯导学习咨询

### ISSUE THREAD

**Issue by lukcyliu** [yuzhou42/GPS-INS-Integrated-Navigation#1]
你好~，我之前稍微接触过一点惯性导航的知识，看了你的工程之后，发现你的数据都很好。我对比了原始传感数据，经旋转矩阵旋转后的Fn比力和积分的速度，发现你的数据波形都很好，而我自己通过推动椅子采集的数据，经过旋转后的Fn比力很飘，所以积分出来的速度也很不好。于是我又对比了欧拉角的输出，你的角度输出是稳定的上下震荡波形，而我的欧拉角就乱的不行了。所以想请教一下你，是不是数据采集过程有什么滤波讲究?
可能我问题描述的比较乱，因为我觉得我的工程存在的问题比较多，如果方便，是否能留下你的邮箱，方便我后续咨询请教你呢？谢谢~
我的邮箱为funkylc@163.com

**Comment by yuzhou42** [comment]
我的邮箱yu.nico.zhou@gmail.com， 我的数据只是原始数据，应该是传感器比较好。。。

**Comment by Wangshida** [comment]
你好，NicoChou师姐，非常感谢您分享的组合导航工程，作为初学者受益匪浅，有一个问题请教师姐，陀螺仪和加速度计的误差漂移相关时间是如何确定的？我看文章是用自相关函数分析的方法，您是这样分析的吗，分析的时候原始数据要做降噪处理等操作吗，有分析的这个的工具箱吗？谢谢，祝生活愉快，天天开心

**Comment by yuzhou42** [comment]
你好，我的误差漂移相关时间是根据传感器手册确定的，没有了解过相关工具...

**Comment by Wangshida** [comment]
好的，我再学习一下，谢谢啦!

**Comment by huazai665** [comment]
你好，我想问下你用的IMU和GPS的型号？

**Comment by lukcyliu** [comment]
jy901，华大北斗导航芯片




| |
刘淳
邮箱：funkylc@163.com
|

签名由 网易邮箱大师 定制

在2018年06月23日 22:51，huazai665 写道：

你好，我想问下你用的IMU和GPS的型号？

**Comment by huazai665** [comment]
你好，你是刚入门导航的小白，我看了你的工程代码，有些地方代码看不懂，不知道是根据哪个公式来的，能不能提供下你建模用的公式，或者告诉我去哪几本书里可以找到，谢谢

**Comment by lukcyliu** [comment]
可以看看严恭敏的讲义，捷联惯导里讲述离散过程连续化的部分。常用的就是一阶马尔科夫。


| |
刘淳
邮箱：funkylc@163.com
|

签名由 网易邮箱大师 定制

在2018年06月25日 15:35，huazai665 写道：

你好，你是刚入门导航的小白，我看了你的工程代码，有些地方代码看不懂，不知道是根据哪个公式来的，能不能提供下你建模用的公式，或者告诉我去哪几本书里可以找到，谢谢
