### ISSUE TITLE
数据采集请教

### ISSUE THREAD

**Issue by daidai-bit** [yuzhou42/GPS-INS-Integrated-Navigation#10]
你好，请问数据Data里GPS三维测速您如何得到，我测得的是GPS一维速度，怎么转换到该坐标系下呢？烦请告知，谢谢。

**Comment by yuzhou42** [comment]
> 你好，请问数据Data里GPS三维测速您如何得到，我测得的是GPS一维速度，怎么转换到该坐标系下呢？烦请告知，谢谢。

这个是传感器直接输出的好像， 你要具体看下你的数据说明来转吧。
