### ISSUE TITLE
滤波问题请教

### ISSUE THREAD

**Issue by daidai-bit** [yuzhou42/GPS-INS-Integrated-Navigation#11]
你好，请问关于代码中惯导系统误差参数以及滤波器噪声设定，您是如何选取的，有资料参考吗？

**Comment by yuzhou42** [comment]
> 你好，请问关于代码中惯导系统误差参数以及滤波器噪声设定，您是如何选取的，有资料参考吗？

建议看一下 [Quaternion kinematics for the error-state Kalman filter](http://www.iri.upc.edu/people/jsola/JoanSola/objectes/notes/kinematics.pdf)

**Comment by daidai-bit** [comment]
> > 你好，请问关于代码中惯导系统误差参数以及滤波器噪声设定，您是如何选取的，有资料参考吗？
> 
> 建议看一下 [Quaternion kinematics for the error-state Kalman filter](http://www.iri.upc.edu/people/jsola/JoanSola/objectes/notes/kinematics.pdf)

谢谢啊
