### ISSUE TITLE
Cant download the data files

### ISSUE THREAD

**Issue by ghost** [yuzhou42/GPS-INS-Integrated-Navigation#6]
hi 
I cant download the data file from the website you have mentioned. would you please make datas available?

**Comment by yuzhou42** [comment]
Hi, sorry for the late reply. Try this [link](https://drive.google.com/open?id=1opU5L2IdCs-FJpqHvzAba_W550uSlNzW) out. It's on my Google drive now.

**Comment by ghost** [comment]
Thank you so much

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by zdymdd** [comment]
hi ,I cant download the data file from the website you have mentioned. would you please make datas available?This is my email address:  <mddazhj1314@qq.com>
