### ISSUE TITLE
请问这套代码有相关的论文吗

### ISSUE THREAD

**Issue by sentiment0** [yuzhou42/GPS-INS-Integrated-Navigation#8]
这套代码里的状态转移矩阵之类的，我有些理解不了，所以想请问您有没有对应论文可以参考？

**Comment by yuzhou42** [comment]
> 这套代码里的状态转移矩阵之类的，我有些理解不了，所以想请问您有没有对应论文可以参考？
可以参考一下秦永元惯性导航那本书， 还有[John Sola](http://www.joansola.eu/) 的一些教程。
