### ISSUE TITLE
经纬度更新的问题

### ISSUE THREAD

**Issue by Jasonabac** [yuzhou42/GPS-INS-Integrated-Navigation#9]
你好， 在主程序main_Nav 的124 和125 行， 更行经纬度时，请问系数0.29 和0.32 如何求得。谢谢

**Comment by yuzhou42** [comment]
> 你好， 在主程序main_Nav 的124 和125 行， 更行经纬度时，请问系数0.29 和0.32 如何求得。谢谢

我这个应该是当时手动调的...
